{% set name = "test_anaconda" %}
{% set version = "0.3" %}

package:
    name: {{ name|lower }}
    version: {{ version }}
source:
    git_url: https://github.com/sepandhaghighi/test_anaconda
    git_rev: v{{ version }}
build:
    noarch: python
    number: 0
    script: {{ PYTHON }} -m pip install . -vv
requirements:
    host:
        - pip
        - python >=3.5
    run:
        - python >=3.5
about:
    home: https://github.com/sepandhaghighi/test_anaconda
    license: MIT
    license_family: MIT
    summary: Test Anaconda
extra:
    recipe-maintainers:
        - sepandhaghighi
